### ISSUE TITLE
Review labels

### ISSUE THREAD

**Issue by lucenasj** [sitmun/sitmun-admin-app#58]
- [x] USER Edit - "Password set" label #62
- [x] USER Edit - "Last name" label #63
- [x] LAYER page - Headers #42
- [x] CONNEXIÓ - Tasques 
- [x] LAYER - layer field configuration  #21

- [x] SERVICE.  Paràmetres de configuració → Paràmetres de configuració del servei
- [x] SERVICE.  Selecciona les capes que vols donar d’alta → Capes del servei

- [x] LAYER.  Informació → Informacio alfanumèrica de la capa
- [x] LAYER.  Selecció espacial → Configuració de la selecció espacial
- [x] LAYER.  Configuració de paràmetres → Configuració atributs alfanumèrics
- [x] LAYER.  Filtres → Configuració de filtres
- [x] LAYER.  Estils → Configuració d’estils
- [x] LAYER.  Territori → Territoris amb accés a la capa
- [x] LAYER.  Configuració de permisos sobre les capes → Grups de permisos i Rols que tenen accés a la capa
- [x] LAYER.  Nodes → Arbres i Nodes que contenen la capa.  

- [x] BASE MAP.  Configuració de cartografies → Capes que formen part d’aquest mapa de fons
- [x] BASE MAP.  Rols → Rols que tenen permís d’accés sobre aquest mapa de fons
 
- [x] LAYER PERMISSION. Configuració de cartografies → Capes que formen part d’aquest grup de permís-
- [x] LAYER PERMISSION. Rols → Rols que tenen permís d’accés sobre aquest grup de permís.

- [x] TERRITORY.  Permisos→ Rols i usuaris amb accés a aquest territori
- [x] TERRITORY.  Cartografia → Capes a les quals té accés aquest territori
- [x] TERRITORY.  Tasca → Tasques a les quals té accés aquest territori

- [x] ROLE.  Configuració de permisos sobre capes→ Capes a les que té accés aquest territori
- [x] ROLE. Aplicacions → Aplicacions a les quals té accés aquest rol
- [x] ROLE. Tasques → Tasques a les quals té accés aquest rol
- [x] ROLE. Combinació de territori i usuaris 

- [x] USER. Permisos → Territoris i Rols als quals té accés aquest usuari
- [x] USER. Dades associades al territori
- [x] USER. Aplicacions a les quals té accés aquest usuari

 - [x] TASK.  Rols → Rols que tenen accés a aquesta tasca
 - [x] TASK. Territori→ Territoris que tenen accés a aquesta tasca
 - [x] TASK. Paràmetres → Paràmetres de la tasca 

- [x] APP. Rols → Rols que tenen accés a aquesta aplicació
- [x] APP. Fons→ Mapes de fons disponibles a l’aplicació
- [x]  APP.  Arbre → Arbres disponibles a l’aplicació

**Comment by ibarzrm** [comment]
We would like to propose as an improvement, to change some labels to make the functionality more intuitive. 
This would be the case of the label “Capes a les quals té accés aquest territori” for “**Capes disponibles per aquest territori**” inside the edition panel of a territory, and also “Territoris amb accés a la capa” for “**Territoris amb disponibilitat a la capa**” inside the panel of each layer.

**Comment by fjlopez** [comment]
This should be straightforward to implement. Could you coordinate with @codinachssm and @RicardCots to prepare a list of labels for discussion? Once finalized, we can apply this change to the dev branch.

**Comment by fjlopez** [comment]
Closed for lack of activity

**Comment by ibarzrm** [comment]
We are reopening this case to propose changing the label in the side menu, which is currently in Catalan as "**Permisos sobre les capes**" and we would change it to "**Permisos a capes**" so that it does not appear on a second line.

Now:

<img width="224" height="596" alt="Image" src="https://github.com/user-attachments/assets/b2f2dac6-9bec-4391-85ff-ee4577c6909e" />

After:

<img width="232" height="621" alt="Image" src="https://github.com/user-attachments/assets/a546e843-8cb9-414a-a5ff-8756fef1cce3" />

Something similar probably happens in other languages as well.

**Comment by ibarzrm** [comment]
Reopen issue
