### ISSUE TITLE
Review missing columns

### ISSUE THREAD

**Issue by lucenasj** [sitmun/sitmun-admin-app#59]
- [x] USER - Edition (pos_type missing) https://github.com/sitmun/sitmun-admin-app/issues/53
- [x] CONNECTION - Tasks https://github.com/sitmun/sitmun-admin-app/issues/48
- [x] TASKS - Territory #54
- [x] TERRITORY - TerType #50
- [x] LAYER - GEO_SOURCE (Grouping source) #76
- [x]  TASK-EXTRACTION FME - Name #125

**Comment by lucenasj** [comment]
- [ ] https://github.com/sitmun/sitmun-admin-app/issues/53
